---
- name: Install nix
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install wget
      command: "sudo pacman --noconfirm -Sq wget"
    - name: Download nix installer
      command: "wget https://nixos.org/nix/install"
    - name: Install nix
      command: "bash ./install"
    - name: Add home manager channel
      shell: "echo $PATH && nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager"
      args:
        executable: /bin/bash
      environment:
        PATH: "/home/ubuntu/.nix-profile/bin:{{ ansible_env.PATH }}"
    - name: Update nix sources
      shell: "nix-channel --update"
      args:
        executable: /bin/bash
      environment:
        PATH: "/home/ubuntu/.nix-profile/bin:{{ ansible_env.PATH }}"
    - name: Workaround for temporary home-manager bug
      shell: "mkdir -m 0755 -p /nix/var/nix/{profiles,gcroots}/per-user/ubuntu"
      args:
        executable: /bin/bash
    - name: Download nix installer
      command: "mkdir -p ~/.config/nixpkgs/"
    - name: Copy home.nix
      ansible.builtin.copy:
        src: ./home.nix
        dest: ~/.config/home-manager/home.nix
    - name: Copy nix directory
      ansible.builtin.copy:
        src: ./nix
        dest: ~/
    - name: Install home manager
      shell: "nix-shell '<home-manager>' -A install"
      args:
        executable: /bin/bash
      environment:
        PATH: "/home/ubuntu/.nix-profile/bin:{{ ansible_env.PATH }}"
        NIX_PATH: "/home/ubuntu/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/ubuntu/channels"
